# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_app.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 633)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("*{\n"
"    background-color: rgb(48, 48, 48);\n"
"border:none;\n"
"}")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"background-color: rgb(48, 48, 48);")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu.setGeometry(QtCore.QRect(0, 0, 170, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_menu.sizePolicy().hasHeightForWidth())
        self.frame_menu.setSizePolicy(sizePolicy)
        self.frame_menu.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.botonInicio = QtWidgets.QPushButton(self.frame_menu)
        self.botonInicio.setGeometry(QtCore.QRect(0, 0, 81, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonInicio.sizePolicy().hasHeightForWidth())
        self.botonInicio.setSizePolicy(sizePolicy)
        self.botonInicio.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"    border-image: url(:/cct/iconos/home.png);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.botonInicio.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cct/iconos/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonInicio.setIcon(icon)
        self.botonInicio.setCheckable(False)
        self.botonInicio.setAutoRepeat(False)
        self.botonInicio.setAutoExclusive(False)
        self.botonInicio.setObjectName("botonInicio")
        self.menu = QtWidgets.QToolBox(self.frame_menu)
        self.menu.setGeometry(QtCore.QRect(0, 80, 191, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.menu.setObjectName("menu")
        self.Sensor1 = QtWidgets.QWidget()
        self.Sensor1.setGeometry(QtCore.QRect(0, 0, 191, 127))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sensor1.sizePolicy().hasHeightForWidth())
        self.Sensor1.setSizePolicy(sizePolicy)
        self.Sensor1.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Sensor1.setObjectName("Sensor1")
        self.boton1_1 = QtWidgets.QPushButton(self.Sensor1)
        self.boton1_1.setGeometry(QtCore.QRect(0, 0, 191, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton1_1.sizePolicy().hasHeightForWidth())
        self.boton1_1.setSizePolicy(sizePolicy)
        self.boton1_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.boton1_1.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/cct/iconos/numbered-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton1_1.setIcon(icon1)
        self.boton1_1.setObjectName("boton1_1")
        self.boton1_2 = QtWidgets.QPushButton(self.Sensor1)
        self.boton1_2.setGeometry(QtCore.QRect(0, 30, 191, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton1_2.sizePolicy().hasHeightForWidth())
        self.boton1_2.setSizePolicy(sizePolicy)
        self.boton1_2.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/cct/iconos/bar-graph-on-a-rectangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton1_2.setIcon(icon2)
        self.boton1_2.setObjectName("boton1_2")
        self.boton1_3 = QtWidgets.QPushButton(self.Sensor1)
        self.boton1_3.setGeometry(QtCore.QRect(0, 60, 191, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton1_3.sizePolicy().hasHeightForWidth())
        self.boton1_3.setSizePolicy(sizePolicy)
        self.boton1_3.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/cct/iconos/table-grid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton1_3.setIcon(icon3)
        self.boton1_3.setObjectName("boton1_3")
        self.boton1_4 = QtWidgets.QPushButton(self.Sensor1)
        self.boton1_4.setGeometry(QtCore.QRect(0, 90, 191, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton1_4.sizePolicy().hasHeightForWidth())
        self.boton1_4.setSizePolicy(sizePolicy)
        self.boton1_4.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/cct/iconos/cloud-storage-download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton1_4.setIcon(icon4)
        self.boton1_4.setObjectName("boton1_4")
        self.boton1_2.raise_()
        self.boton1_3.raise_()
        self.boton1_1.raise_()
        self.boton1_4.raise_()
        self.menu.addItem(self.Sensor1, "")
        self.Sensor2 = QtWidgets.QWidget()
        self.Sensor2.setGeometry(QtCore.QRect(0, 0, 191, 127))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sensor2.sizePolicy().hasHeightForWidth())
        self.Sensor2.setSizePolicy(sizePolicy)
        self.Sensor2.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.Sensor2.setObjectName("Sensor2")
        self.boton2_1 = QtWidgets.QPushButton(self.Sensor2)
        self.boton2_1.setGeometry(QtCore.QRect(0, 0, 191, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton2_1.sizePolicy().hasHeightForWidth())
        self.boton2_1.setSizePolicy(sizePolicy)
        self.boton2_1.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        self.boton2_1.setIcon(icon1)
        self.boton2_1.setObjectName("boton2_1")
        self.menu.addItem(self.Sensor2, "")
        self.ModoAuto = QtWidgets.QWidget()
        self.ModoAuto.setGeometry(QtCore.QRect(0, 0, 191, 127))
        self.ModoAuto.setObjectName("ModoAuto")
        self.boton_auto = QtWidgets.QPushButton(self.ModoAuto)
        self.boton_auto.setGeometry(QtCore.QRect(0, 0, 171, 30))
        self.boton_auto.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/cct/iconos/leter-a-inside-a-black-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_auto.setIcon(icon5)
        self.boton_auto.setObjectName("boton_auto")
        self.menu.addItem(self.ModoAuto, "")
        self.Subir_Nube_Conf = QtWidgets.QWidget()
        self.Subir_Nube_Conf.setGeometry(QtCore.QRect(0, 0, 191, 127))
        self.Subir_Nube_Conf.setObjectName("Subir_Nube_Conf")
        self.boton_configuracion_nube = QtWidgets.QPushButton(self.Subir_Nube_Conf)
        self.boton_configuracion_nube.setGeometry(QtCore.QRect(0, 0, 171, 30))
        self.boton_configuracion_nube.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/cct/iconos/user_setting_settings_icon_148607.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_configuracion_nube.setIcon(icon6)
        self.boton_configuracion_nube.setObjectName("boton_configuracion_nube")
        self.menu.addItem(self.Subir_Nube_Conf, "")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(170, 20, 730, 620))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(730, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home.sizePolicy().hasHeightForWidth())
        self.home.setSizePolicy(sizePolicy)
        self.home.setObjectName("home")
        self.frame_1 = QtWidgets.QFrame(self.home)
        self.frame_1.setGeometry(QtCore.QRect(0, 10, 761, 651))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_1.sizePolicy().hasHeightForWidth())
        self.frame_1.setSizePolicy(sizePolicy)
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.nombre_sensor1 = QtWidgets.QLabel(self.frame_1)
        self.nombre_sensor1.setGeometry(QtCore.QRect(90, 270, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nombre_sensor1.sizePolicy().hasHeightForWidth())
        self.nombre_sensor1.setSizePolicy(sizePolicy)
        self.nombre_sensor1.setObjectName("nombre_sensor1")
        self.nombre_sensor2 = QtWidgets.QLabel(self.frame_1)
        self.nombre_sensor2.setGeometry(QtCore.QRect(440, 270, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nombre_sensor2.sizePolicy().hasHeightForWidth())
        self.nombre_sensor2.setSizePolicy(sizePolicy)
        self.nombre_sensor2.setObjectName("nombre_sensor2")
        self.boton_sensor1 = QtWidgets.QPushButton(self.frame_1)
        self.boton_sensor1.setGeometry(QtCore.QRect(100, 70, 170, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_sensor1.sizePolicy().hasHeightForWidth())
        self.boton_sensor1.setSizePolicy(sizePolicy)
        self.boton_sensor1.setStyleSheet("border-image: url(:/cct/iconos/sensor1.png);")
        self.boton_sensor1.setText("")
        self.boton_sensor1.setObjectName("boton_sensor1")
        self.boton_sensor2 = QtWidgets.QPushButton(self.frame_1)
        self.boton_sensor2.setGeometry(QtCore.QRect(410, 60, 240, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_sensor2.sizePolicy().hasHeightForWidth())
        self.boton_sensor2.setSizePolicy(sizePolicy)
        self.boton_sensor2.setStyleSheet("border-image: url(:/cct/iconos/bombilla.png);")
        self.boton_sensor2.setText("")
        self.boton_sensor2.setObjectName("boton_sensor2")
        self.mensaje_emparejar = QtWidgets.QLineEdit(self.frame_1)
        self.mensaje_emparejar.setGeometry(QtCore.QRect(40, 390, 291, 32))
        self.mensaje_emparejar.setAlignment(QtCore.Qt.AlignCenter)
        self.mensaje_emparejar.setReadOnly(True)
        self.mensaje_emparejar.setObjectName("mensaje_emparejar")
        self.mensaje_emparejar_bombilla = QtWidgets.QLineEdit(self.frame_1)
        self.mensaje_emparejar_bombilla.setGeometry(QtCore.QRect(410, 390, 291, 32))
        self.mensaje_emparejar_bombilla.setAlignment(QtCore.Qt.AlignCenter)
        self.mensaje_emparejar_bombilla.setReadOnly(True)
        self.mensaje_emparejar_bombilla.setObjectName("mensaje_emparejar_bombilla")
        self.frame_9 = QtWidgets.QFrame(self.frame_1)
        self.frame_9.setGeometry(QtCore.QRect(120, 310, 141, 51))
        self.frame_9.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.boton_emparejar = QtWidgets.QPushButton(self.frame_9)
        self.boton_emparejar.setGeometry(QtCore.QRect(0, 0, 141, 51))
        self.boton_emparejar.setStyleSheet("QPushButton{\n"
"    font: 75 italic 14pt \"PibotoLt\";\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"font: 75 italic 14pt \"PibotoLt\";")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/cct/iconos/pair.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_emparejar.setIcon(icon7)
        self.boton_emparejar.setObjectName("boton_emparejar")
        self.frame_10 = QtWidgets.QFrame(self.frame_1)
        self.frame_10.setGeometry(QtCore.QRect(470, 310, 141, 51))
        self.frame_10.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.boton_emparejar_bombilla = QtWidgets.QPushButton(self.frame_10)
        self.boton_emparejar_bombilla.setGeometry(QtCore.QRect(0, 0, 141, 51))
        self.boton_emparejar_bombilla.setStyleSheet("QPushButton{\n"
"    font: 75 italic 14pt \"PibotoLt\";\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        self.boton_emparejar_bombilla.setIcon(icon7)
        self.boton_emparejar_bombilla.setObjectName("boton_emparejar_bombilla")
        self.frame_11 = QtWidgets.QFrame(self.frame_1)
        self.frame_11.setGeometry(QtCore.QRect(270, 480, 191, 61))
        self.frame_11.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.boton_buscar = QtWidgets.QPushButton(self.frame_11)
        self.boton_buscar.setGeometry(QtCore.QRect(0, 0, 191, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_buscar.sizePolicy().hasHeightForWidth())
        self.boton_buscar.setSizePolicy(sizePolicy)
        self.boton_buscar.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"\n"
"\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/cct/iconos/bluetooth_111074.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_buscar.setIcon(icon8)
        self.boton_buscar.setIconSize(QtCore.QSize(35, 35))
        self.boton_buscar.setObjectName("boton_buscar")
        self.stackedWidget.addWidget(self.home)
        self.sensor1_1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor1_1.sizePolicy().hasHeightForWidth())
        self.sensor1_1.setSizePolicy(sizePolicy)
        self.sensor1_1.setObjectName("sensor1_1")
        self.frame_2 = QtWidgets.QFrame(self.sensor1_1)
        self.frame_2.setGeometry(QtCore.QRect(20, -20, 741, 681))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.medidaautomatica = QtWidgets.QCheckBox(self.frame_2)
        self.medidaautomatica.setGeometry(QtCore.QRect(170, 500, 281, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.medidaautomatica.sizePolicy().hasHeightForWidth())
        self.medidaautomatica.setSizePolicy(sizePolicy)
        self.medidaautomatica.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.medidaautomatica.setObjectName("medidaautomatica")
        self.Temperatura = QtWidgets.QLineEdit(self.frame_2)
        self.Temperatura.setGeometry(QtCore.QRect(320, 159, 140, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Temperatura.sizePolicy().hasHeightForWidth())
        self.Temperatura.setSizePolicy(sizePolicy)
        self.Temperatura.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Temperatura.setAlignment(QtCore.Qt.AlignCenter)
        self.Temperatura.setReadOnly(True)
        self.Temperatura.setObjectName("Temperatura")
        self.Humedad = QtWidgets.QLineEdit(self.frame_2)
        self.Humedad.setGeometry(QtCore.QRect(320, 223, 140, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Humedad.sizePolicy().hasHeightForWidth())
        self.Humedad.setSizePolicy(sizePolicy)
        self.Humedad.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Humedad.setAlignment(QtCore.Qt.AlignCenter)
        self.Humedad.setReadOnly(True)
        self.Humedad.setObjectName("Humedad")
        self.Bateria = QtWidgets.QLineEdit(self.frame_2)
        self.Bateria.setGeometry(QtCore.QRect(320, 287, 140, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bateria.sizePolicy().hasHeightForWidth())
        self.Bateria.setSizePolicy(sizePolicy)
        self.Bateria.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Bateria.setAlignment(QtCore.Qt.AlignCenter)
        self.Bateria.setReadOnly(True)
        self.Bateria.setObjectName("Bateria")
        self.Voltaje = QtWidgets.QLineEdit(self.frame_2)
        self.Voltaje.setGeometry(QtCore.QRect(320, 350, 140, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Voltaje.sizePolicy().hasHeightForWidth())
        self.Voltaje.setSizePolicy(sizePolicy)
        self.Voltaje.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Voltaje.setAlignment(QtCore.Qt.AlignCenter)
        self.Voltaje.setReadOnly(True)
        self.Voltaje.setObjectName("Voltaje")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(270, 50, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(111, 151, 133, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox.setGeometry(QtCore.QRect(450, 500, 50, 31))
        self.spinBox.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(900)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setDisplayIntegerBase(10)
        self.spinBox.setObjectName("spinBox")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(500, 500, 41, 31))
        self.label_9.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_9.setObjectName("label_9")
        self.mensaje_sensor = QtWidgets.QLineEdit(self.frame_2)
        self.mensaje_sensor.setGeometry(QtCore.QRect(200, 90, 331, 32))
        self.mensaje_sensor.setAlignment(QtCore.Qt.AlignCenter)
        self.mensaje_sensor.setReadOnly(True)
        self.mensaje_sensor.setObjectName("mensaje_sensor")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(50, 150, 51, 51))
        self.frame.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-image: url(:/cct/iconos/thermometer-temperature-control-tool-weather-interface-symbol_icon-icons.com_54635.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(50, 220, 51, 41))
        self.frame_3.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-image: url(:/cct/iconos/humedad.png);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(50, 350, 51, 51))
        self.frame_4.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-image: url(:/cct/iconos/klipartz.com (1).png);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(50, 280, 51, 51))
        self.frame_5.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-image: url(:/cct/iconos/klipartz.com.png);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_12 = QtWidgets.QFrame(self.frame_2)
        self.frame_12.setGeometry(QtCore.QRect(530, 250, 101, 61))
        self.frame_12.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.botonMedida = QtWidgets.QPushButton(self.frame_12)
        self.botonMedida.setGeometry(QtCore.QRect(0, 0, 101, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonMedida.sizePolicy().hasHeightForWidth())
        self.botonMedida.setSizePolicy(sizePolicy)
        self.botonMedida.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/cct/iconos/medida.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonMedida.setIcon(icon9)
        self.botonMedida.setObjectName("botonMedida")
        self.stackedWidget.addWidget(self.sensor1_1)
        self.sensor1_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor1_2.sizePolicy().hasHeightForWidth())
        self.sensor1_2.setSizePolicy(sizePolicy)
        self.sensor1_2.setObjectName("sensor1_2")
        self.label_6 = QtWidgets.QLabel(self.sensor1_2)
        self.label_6.setGeometry(QtCore.QRect(270, 30, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.grafica = Grafica(self.sensor1_2)
        self.grafica.setGeometry(QtCore.QRect(40, 80, 641, 471))
        self.grafica.setObjectName("grafica")
        self.frame_21 = QtWidgets.QFrame(self.sensor1_2)
        self.frame_21.setGeometry(QtCore.QRect(50, 560, 231, 41))
        self.frame_21.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.mostrar_mas_precision = QtWidgets.QPushButton(self.frame_21)
        self.mostrar_mas_precision.setGeometry(QtCore.QRect(0, 0, 241, 43))
        self.mostrar_mas_precision.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        self.mostrar_mas_precision.setObjectName("mostrar_mas_precision")
        self.stackedWidget.addWidget(self.sensor1_2)
        self.sensor1_3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor1_3.sizePolicy().hasHeightForWidth())
        self.sensor1_3.setSizePolicy(sizePolicy)
        self.sensor1_3.setObjectName("sensor1_3")
        self.label_7 = QtWidgets.QLabel(self.sensor1_3)
        self.label_7.setGeometry(QtCore.QRect(270, 30, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.tabla_sensor = QtWidgets.QTableWidget(self.sensor1_3)
        self.tabla_sensor.setGeometry(QtCore.QRect(30, 70, 651, 431))
        self.tabla_sensor.setAutoFillBackground(False)
        self.tabla_sensor.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.tabla_sensor.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tabla_sensor.setObjectName("tabla_sensor")
        self.tabla_sensor.setColumnCount(5)
        self.tabla_sensor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_sensor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_sensor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_sensor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_sensor.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_sensor.setHorizontalHeaderItem(4, item)
        self.tabla_sensor.horizontalHeader().setDefaultSectionSize(130)
        self.frame_13 = QtWidgets.QFrame(self.sensor1_3)
        self.frame_13.setGeometry(QtCore.QRect(170, 520, 120, 41))
        self.frame_13.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.boton_borrartabla_ultimo = QtWidgets.QPushButton(self.frame_13)
        self.boton_borrartabla_ultimo.setGeometry(QtCore.QRect(0, 0, 121, 41))
        self.boton_borrartabla_ultimo.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/cct/iconos/borrar ultimo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_borrartabla_ultimo.setIcon(icon10)
        self.boton_borrartabla_ultimo.setObjectName("boton_borrartabla_ultimo")
        self.frame_14 = QtWidgets.QFrame(self.sensor1_3)
        self.frame_14.setGeometry(QtCore.QRect(450, 520, 120, 41))
        self.frame_14.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.boton_borrartabla_entera = QtWidgets.QPushButton(self.frame_14)
        self.boton_borrartabla_entera.setGeometry(QtCore.QRect(0, 0, 121, 41))
        self.boton_borrartabla_entera.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/cct/iconos/borrar todo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_borrartabla_entera.setIcon(icon11)
        self.boton_borrartabla_entera.setObjectName("boton_borrartabla_entera")
        self.stackedWidget.addWidget(self.sensor1_3)
        self.sensor1_4 = QtWidgets.QWidget()
        self.sensor1_4.setObjectName("sensor1_4")
        self.Listar_Datos = QtWidgets.QTextEdit(self.sensor1_4)
        self.Listar_Datos.setGeometry(QtCore.QRect(240, 70, 451, 521))
        self.Listar_Datos.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Listar_Datos.setReadOnly(True)
        self.Listar_Datos.setObjectName("Listar_Datos")
        self.frame_6 = QtWidgets.QFrame(self.sensor1_4)
        self.frame_6.setGeometry(QtCore.QRect(30, 380, 181, 51))
        self.frame_6.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.boton_VisualizarDatos = QtWidgets.QPushButton(self.frame_6)
        self.boton_VisualizarDatos.setGeometry(QtCore.QRect(0, 0, 181, 51))
        self.boton_VisualizarDatos.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/cct/iconos/magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_VisualizarDatos.setIcon(icon12)
        self.boton_VisualizarDatos.setObjectName("boton_VisualizarDatos")
        self.frame_7 = QtWidgets.QFrame(self.sensor1_4)
        self.frame_7.setGeometry(QtCore.QRect(30, 310, 181, 51))
        self.frame_7.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.boton_BorrarDatos = QtWidgets.QPushButton(self.frame_7)
        self.boton_BorrarDatos.setGeometry(QtCore.QRect(0, 0, 181, 51))
        self.boton_BorrarDatos.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        self.boton_BorrarDatos.setIcon(icon11)
        self.boton_BorrarDatos.setObjectName("boton_BorrarDatos")
        self.frame_8 = QtWidgets.QFrame(self.sensor1_4)
        self.frame_8.setGeometry(QtCore.QRect(30, 230, 181, 51))
        self.frame_8.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.boton_CargarDatos = QtWidgets.QPushButton(self.frame_8)
        self.boton_CargarDatos.setGeometry(QtCore.QRect(0, 0, 181, 51))
        self.boton_CargarDatos.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}")
        self.boton_CargarDatos.setIcon(icon4)
        self.boton_CargarDatos.setObjectName("boton_CargarDatos")
        self.label_8 = QtWidgets.QLabel(self.sensor1_4)
        self.label_8.setGeometry(QtCore.QRect(270, 30, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.sensor1_4)
        self.sensor2_1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor2_1.sizePolicy().hasHeightForWidth())
        self.sensor2_1.setSizePolicy(sizePolicy)
        self.sensor2_1.setObjectName("sensor2_1")
        self.nombre_sensor2_2 = QtWidgets.QLabel(self.sensor2_1)
        self.nombre_sensor2_2.setGeometry(QtCore.QRect(270, 30, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nombre_sensor2_2.sizePolicy().hasHeightForWidth())
        self.nombre_sensor2_2.setSizePolicy(sizePolicy)
        self.nombre_sensor2_2.setObjectName("nombre_sensor2_2")
        self.label_10 = QtWidgets.QLabel(self.sensor2_1)
        self.label_10.setGeometry(QtCore.QRect(180, 350, 281, 51))
        self.label_10.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_10.setObjectName("label_10")
        self.textEdit = QtWidgets.QTextEdit(self.sensor2_1)
        self.textEdit.setGeometry(QtCore.QRect(460, 350, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.textEdit.setObjectName("textEdit")
        self.mensaje_brillo = QtWidgets.QLineEdit(self.sensor2_1)
        self.mensaje_brillo.setGeometry(QtCore.QRect(260, 420, 371, 32))
        self.mensaje_brillo.setAlignment(QtCore.Qt.AlignCenter)
        self.mensaje_brillo.setReadOnly(True)
        self.mensaje_brillo.setObjectName("mensaje_brillo")
        self.label_16 = QtWidgets.QLabel(self.sensor2_1)
        self.label_16.setGeometry(QtCore.QRect(120, 350, 61, 51))
        self.label_16.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-image: url(:/cct/iconos/brillo.png);")
        self.label_16.setObjectName("label_16")
        self.mensaje_bombilla = QtWidgets.QLineEdit(self.sensor2_1)
        self.mensaje_bombilla.setGeometry(QtCore.QRect(200, 70, 331, 32))
        self.mensaje_bombilla.setAlignment(QtCore.Qt.AlignCenter)
        self.mensaje_bombilla.setReadOnly(True)
        self.mensaje_bombilla.setObjectName("mensaje_bombilla")
        self.frame_15 = QtWidgets.QFrame(self.sensor2_1)
        self.frame_15.setGeometry(QtCore.QRect(150, 180, 111, 71))
        self.frame_15.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.boton_on = QtWidgets.QPushButton(self.frame_15)
        self.boton_on.setGeometry(QtCore.QRect(0, 0, 111, 71))
        self.boton_on.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/cct/iconos/light-bulb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_on.setIcon(icon13)
        self.boton_on.setObjectName("boton_on")
        self.frame_16 = QtWidgets.QFrame(self.sensor2_1)
        self.frame_16.setGeometry(QtCore.QRect(470, 180, 111, 71))
        self.frame_16.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.boton_off = QtWidgets.QPushButton(self.frame_16)
        self.boton_off.setGeometry(QtCore.QRect(0, 0, 111, 71))
        self.boton_off.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        self.boton_off.setIcon(icon13)
        self.boton_off.setObjectName("boton_off")
        self.frame_17 = QtWidgets.QFrame(self.sensor2_1)
        self.frame_17.setGeometry(QtCore.QRect(560, 350, 101, 51))
        self.frame_17.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.boton_brillo = QtWidgets.QPushButton(self.frame_17)
        self.boton_brillo.setGeometry(QtCore.QRect(0, 0, 101, 51))
        self.boton_brillo.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/cct/iconos/aplicar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_brillo.setIcon(icon14)
        self.boton_brillo.setObjectName("boton_brillo")
        self.stackedWidget.addWidget(self.sensor2_1)
        self.Pagina_Auto = QtWidgets.QWidget()
        self.Pagina_Auto.setObjectName("Pagina_Auto")
        self.label_11 = QtWidgets.QLabel(self.Pagina_Auto)
        self.label_11.setGeometry(QtCore.QRect(140, 230, 231, 41))
        self.label_11.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_11.setObjectName("label_11")
        self.modoAuto = QtWidgets.QCheckBox(self.Pagina_Auto)
        self.modoAuto.setGeometry(QtCore.QRect(500, 270, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modoAuto.sizePolicy().hasHeightForWidth())
        self.modoAuto.setSizePolicy(sizePolicy)
        self.modoAuto.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"font: 75 italic 14pt \"PibotoLt\";")
        self.modoAuto.setObjectName("modoAuto")
        self.label_12 = QtWidgets.QLabel(self.Pagina_Auto)
        self.label_12.setGeometry(QtCore.QRect(150, 310, 221, 41))
        self.label_12.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.Pagina_Auto)
        self.label_13.setGeometry(QtCore.QRect(270, 30, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.spinBox_humedad = QtWidgets.QSpinBox(self.Pagina_Auto)
        self.spinBox_humedad.setGeometry(QtCore.QRect(370, 230, 61, 41))
        self.spinBox_humedad.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.spinBox_humedad.setMinimum(1)
        self.spinBox_humedad.setMaximum(100)
        self.spinBox_humedad.setProperty("value", 1)
        self.spinBox_humedad.setDisplayIntegerBase(10)
        self.spinBox_humedad.setObjectName("spinBox_humedad")
        self.spinBox_brillo = QtWidgets.QSpinBox(self.Pagina_Auto)
        self.spinBox_brillo.setGeometry(QtCore.QRect(370, 310, 61, 41))
        self.spinBox_brillo.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.spinBox_brillo.setMinimum(1)
        self.spinBox_brillo.setMaximum(254)
        self.spinBox_brillo.setProperty("value", 1)
        self.spinBox_brillo.setDisplayIntegerBase(10)
        self.spinBox_brillo.setObjectName("spinBox_brillo")
        self.label_14 = QtWidgets.QLabel(self.Pagina_Auto)
        self.label_14.setGeometry(QtCore.QRect(100, 230, 41, 41))
        self.label_14.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-image: url(:/cct/iconos/tint-drop.png);\n"
"")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.Pagina_Auto)
        self.label_15.setGeometry(QtCore.QRect(100, 310, 51, 41))
        self.label_15.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-image: url(:/cct/iconos/light-bulb.png);\n"
"")
        self.label_15.setObjectName("label_15")
        self.stackedWidget.addWidget(self.Pagina_Auto)
        self.Pagina_Nube = QtWidgets.QWidget()
        self.Pagina_Nube.setObjectName("Pagina_Nube")
        self.frame_18 = QtWidgets.QFrame(self.Pagina_Nube)
        self.frame_18.setGeometry(QtCore.QRect(470, 30, 171, 151))
        self.frame_18.setStyleSheet("border-image: url(:/cct/iconos/1490889640-dropbox_82530.png);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.frame_19 = QtWidgets.QFrame(self.Pagina_Nube)
        self.frame_19.setGeometry(QtCore.QRect(470, 370, 181, 151))
        self.frame_19.setStyleSheet("border-image: url(:/cct/iconos/cayenne.png);")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Pagina_Nube)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 560, 651, 32))
        self.lineEdit_2.setStyleSheet("font: 75 12pt \"PibotoLt\";\n"
"color: rgb(170, 170, 255);\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.frame_20 = QtWidgets.QFrame(self.Pagina_Nube)
        self.frame_20.setGeometry(QtCore.QRect(470, 210, 181, 131))
        self.frame_20.setStyleSheet("border-image: url(:/cct/iconos/kaaiotcloud.png);\n"
"")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.widget = QtWidgets.QWidget(self.Pagina_Nube)
        self.widget.setGeometry(QtCore.QRect(80, -30, 283, 601))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.subirdropbox = QtWidgets.QCheckBox(self.widget)
        self.subirdropbox.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.subirdropbox.setObjectName("subirdropbox")
        self.verticalLayout_2.addWidget(self.subirdropbox)
        self.sincronizarkaaiot = QtWidgets.QCheckBox(self.widget)
        self.sincronizarkaaiot.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.sincronizarkaaiot.setObjectName("sincronizarkaaiot")
        self.verticalLayout_2.addWidget(self.sincronizarkaaiot)
        self.sincronizarcayenne = QtWidgets.QCheckBox(self.widget)
        self.sincronizarcayenne.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.sincronizarcayenne.setObjectName("sincronizarcayenne")
        self.verticalLayout_2.addWidget(self.sincronizarcayenne)
        self.stackedWidget.addWidget(self.Pagina_Nube)
        self.barra_superior = QtWidgets.QFrame(self.centralwidget)
        self.barra_superior.setGeometry(QtCore.QRect(170, 0, 731, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barra_superior.sizePolicy().hasHeightForWidth())
        self.barra_superior.setSizePolicy(sizePolicy)
        self.barra_superior.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.barra_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.barra_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barra_superior.setObjectName("barra_superior")
        self.boton_minimizar = QtWidgets.QPushButton(self.barra_superior)
        self.boton_minimizar.setGeometry(QtCore.QRect(660, 0, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_minimizar.sizePolicy().hasHeightForWidth())
        self.boton_minimizar.setSizePolicy(sizePolicy)
        self.boton_minimizar.setStyleSheet("border-image: url(:/cct/iconos/minus-symbol.png);\n"
"\n"
"")
        self.boton_minimizar.setText("")
        self.boton_minimizar.setObjectName("boton_minimizar")
        self.boton_cerrar = QtWidgets.QPushButton(self.barra_superior)
        self.boton_cerrar.setGeometry(QtCore.QRect(700, 0, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_cerrar.sizePolicy().hasHeightForWidth())
        self.boton_cerrar.setSizePolicy(sizePolicy)
        self.boton_cerrar.setStyleSheet("border-image: url(:/cct/iconos/remove-symbol.png);")
        self.boton_cerrar.setText("")
        self.boton_cerrar.setObjectName("boton_cerrar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.menu.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botonInicio.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/iconos/home.png\"/></p></body></html>"))
        self.boton1_1.setText(_translate("MainWindow", "Datos Actuales"))
        self.boton1_2.setText(_translate("MainWindow", "Gráfica"))
        self.boton1_3.setText(_translate("MainWindow", "Tabla"))
        self.boton1_4.setText(_translate("MainWindow", "Cargar datos"))
        self.menu.setItemText(self.menu.indexOf(self.Sensor1), _translate("MainWindow", "Sensor Xiaomi"))
        self.Sensor2.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.boton2_1.setText(_translate("MainWindow", "Control"))
        self.menu.setItemText(self.menu.indexOf(self.Sensor2), _translate("MainWindow", "Bombilla Philips"))
        self.boton_auto.setText(_translate("MainWindow", "Modo Auto"))
        self.menu.setItemText(self.menu.indexOf(self.ModoAuto), _translate("MainWindow", "Modo Automático"))
        self.boton_configuracion_nube.setText(_translate("MainWindow", "Configuración"))
        self.menu.setItemText(self.menu.indexOf(self.Subir_Nube_Conf), _translate("MainWindow", "Subir Datos Nube"))
        self.nombre_sensor1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Xiaomi LYWSD03MMC</span></p></body></html>"))
        self.nombre_sensor2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Philips Hue Bombilla E27</span></p></body></html>"))
        self.boton_emparejar.setText(_translate("MainWindow", "Emparejar"))
        self.boton_emparejar_bombilla.setText(_translate("MainWindow", "Emparejar"))
        self.boton_buscar.setText(_translate("MainWindow", "Buscar dispositivos"))
        self.medidaautomatica.setText(_translate("MainWindow", "Tomar medida automática cada:"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Xiaomi LYWSD03MMC</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aaaaff;\">Temperatura (ºC)</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aaaaff;\">Humedad (%)</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aaaaff;\">Bateria (%)</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aaaaff;\">Voltaje Bateria (V)</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", " min"))
        self.botonMedida.setText(_translate("MainWindow", "Tomar\n"
" medida"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Xiaomi LYWSD03MMC</span></p></body></html>"))
        self.mostrar_mas_precision.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\">Mostrar gráfica</p><p align=\"center\">temperatura</p></body></html>"))
        self.mostrar_mas_precision.setText(_translate("MainWindow", "Mostrar gráficas con mayor \n"
"precisión"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Xiaomi LYWSD03MMC</span></p></body></html>"))
        item = self.tabla_sensor.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fecha"))
        item = self.tabla_sensor.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hora"))
        item = self.tabla_sensor.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Temperatura (ºC)"))
        item = self.tabla_sensor.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Humedad (%)"))
        item = self.tabla_sensor.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Batería (%)"))
        self.boton_borrartabla_ultimo.setText(_translate("MainWindow", "Borrar último"))
        self.boton_borrartabla_entera.setText(_translate("MainWindow", "Borrar todo"))
        self.boton_VisualizarDatos.setText(_translate("MainWindow", "Visualizar datos \n"
" anteiores"))
        self.boton_BorrarDatos.setText(_translate("MainWindow", "Borrar todos los \n"
" datos anteriores"))
        self.boton_CargarDatos.setText(_translate("MainWindow", "Cargar datos \n"
" anteriores en la tabla"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Xiaomi LYWSD03MMC</span></p></body></html>"))
        self.nombre_sensor2_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Philips Hue Bombilla E27</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Introduce el nivel de brillo deseado </p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.boton_on.setText(_translate("MainWindow", "ON"))
        self.boton_off.setText(_translate("MainWindow", "OFF"))
        self.boton_brillo.setText(_translate("MainWindow", "Aplicar"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Introduce el nivel de humedad </p></body></html>"))
        self.modoAuto.setText(_translate("MainWindow", "Modo auto"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Introduce el nivel de brillo</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Modo Automático</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.lineEdit_2.setText(_translate("MainWindow", "Nota: para usar estas opciones hay que seguir el manual, disponible en el fichero README"))
        self.subirdropbox.setText(_translate("MainWindow", "Subir datos a Dropbox"))
        self.sincronizarkaaiot.setText(_translate("MainWindow", "Sincronizar kaaiot"))
        self.sincronizarcayenne.setText(_translate("MainWindow", "Sincronizar con Cayenne MyDevices"))

from grafica import Grafica
import icons_rc
