# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_app.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 622)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("*{\n"
"    background-color: rgb(48, 48, 48);\n"
"border:none;\n"
"}")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"background-color: rgb(48, 48, 48);")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu.setGeometry(QtCore.QRect(0, 0, 170, 620))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_menu.sizePolicy().hasHeightForWidth())
        self.frame_menu.setSizePolicy(sizePolicy)
        self.frame_menu.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.botonInicio = QtWidgets.QPushButton(self.frame_menu)
        self.botonInicio.setGeometry(QtCore.QRect(0, 0, 81, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonInicio.sizePolicy().hasHeightForWidth())
        self.botonInicio.setSizePolicy(sizePolicy)
        self.botonInicio.setStyleSheet("border-image: url(:/cct/iconos/home.png);\n"
"\n"
"")
        self.botonInicio.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cct/iconos/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonInicio.setIcon(icon)
        self.botonInicio.setCheckable(False)
        self.botonInicio.setAutoRepeat(False)
        self.botonInicio.setAutoExclusive(False)
        self.botonInicio.setObjectName("botonInicio")
        self.menu = QtWidgets.QToolBox(self.frame_menu)
        self.menu.setGeometry(QtCore.QRect(0, 80, 191, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu.sizePolicy().hasHeightForWidth())
        self.menu.setSizePolicy(sizePolicy)
        self.menu.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.menu.setObjectName("menu")
        self.Sensor1 = QtWidgets.QWidget()
        self.Sensor1.setGeometry(QtCore.QRect(0, 0, 191, 93))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sensor1.sizePolicy().hasHeightForWidth())
        self.Sensor1.setSizePolicy(sizePolicy)
        self.Sensor1.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Sensor1.setObjectName("Sensor1")
        self.boton1_1 = QtWidgets.QPushButton(self.Sensor1)
        self.boton1_1.setGeometry(QtCore.QRect(0, 0, 191, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton1_1.sizePolicy().hasHeightForWidth())
        self.boton1_1.setSizePolicy(sizePolicy)
        self.boton1_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.boton1_1.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/cct/iconos/numbered-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton1_1.setIcon(icon1)
        self.boton1_1.setObjectName("boton1_1")
        self.boton1_2 = QtWidgets.QPushButton(self.Sensor1)
        self.boton1_2.setGeometry(QtCore.QRect(0, 30, 191, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton1_2.sizePolicy().hasHeightForWidth())
        self.boton1_2.setSizePolicy(sizePolicy)
        self.boton1_2.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/cct/iconos/bar-graph-on-a-rectangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton1_2.setIcon(icon2)
        self.boton1_2.setObjectName("boton1_2")
        self.boton1_3 = QtWidgets.QPushButton(self.Sensor1)
        self.boton1_3.setGeometry(QtCore.QRect(0, 60, 191, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton1_3.sizePolicy().hasHeightForWidth())
        self.boton1_3.setSizePolicy(sizePolicy)
        self.boton1_3.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/cct/iconos/table-grid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton1_3.setIcon(icon3)
        self.boton1_3.setObjectName("boton1_3")
        self.boton1_2.raise_()
        self.boton1_3.raise_()
        self.boton1_1.raise_()
        self.menu.addItem(self.Sensor1, "")
        self.Sensor2 = QtWidgets.QWidget()
        self.Sensor2.setGeometry(QtCore.QRect(0, 0, 191, 93))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sensor2.sizePolicy().hasHeightForWidth())
        self.Sensor2.setSizePolicy(sizePolicy)
        self.Sensor2.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.Sensor2.setObjectName("Sensor2")
        self.boton2_1 = QtWidgets.QPushButton(self.Sensor2)
        self.boton2_1.setGeometry(QtCore.QRect(0, 0, 191, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton2_1.sizePolicy().hasHeightForWidth())
        self.boton2_1.setSizePolicy(sizePolicy)
        self.boton2_1.setStyleSheet("QPushButton{\n"
"    border-radus:Spx;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(146, 142, 255);\n"
"}\n"
"")
        self.boton2_1.setIcon(icon1)
        self.boton2_1.setObjectName("boton2_1")
        self.menu.addItem(self.Sensor2, "")
        self.ModoAuto = QtWidgets.QWidget()
        self.ModoAuto.setObjectName("ModoAuto")
        self.boton_auto = QtWidgets.QPushButton(self.ModoAuto)
        self.boton_auto.setGeometry(QtCore.QRect(0, 0, 171, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/cct/iconos/leter-a-inside-a-black-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_auto.setIcon(icon4)
        self.boton_auto.setObjectName("boton_auto")
        self.menu.addItem(self.ModoAuto, "")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(180, 30, 730, 620))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(730, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home.sizePolicy().hasHeightForWidth())
        self.home.setSizePolicy(sizePolicy)
        self.home.setObjectName("home")
        self.frame_1 = QtWidgets.QFrame(self.home)
        self.frame_1.setGeometry(QtCore.QRect(0, 10, 761, 651))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_1.sizePolicy().hasHeightForWidth())
        self.frame_1.setSizePolicy(sizePolicy)
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.boton_buscar = QtWidgets.QPushButton(self.frame_1)
        self.boton_buscar.setGeometry(QtCore.QRect(250, 500, 191, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_buscar.sizePolicy().hasHeightForWidth())
        self.boton_buscar.setSizePolicy(sizePolicy)
        self.boton_buscar.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"\n"
"\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/cct/bluetooth_111074.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_buscar.setIcon(icon5)
        self.boton_buscar.setIconSize(QtCore.QSize(35, 35))
        self.boton_buscar.setObjectName("boton_buscar")
        self.nombre_sensor1 = QtWidgets.QLabel(self.frame_1)
        self.nombre_sensor1.setGeometry(QtCore.QRect(90, 270, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nombre_sensor1.sizePolicy().hasHeightForWidth())
        self.nombre_sensor1.setSizePolicy(sizePolicy)
        self.nombre_sensor1.setObjectName("nombre_sensor1")
        self.nombre_sensor2 = QtWidgets.QLabel(self.frame_1)
        self.nombre_sensor2.setGeometry(QtCore.QRect(440, 270, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nombre_sensor2.sizePolicy().hasHeightForWidth())
        self.nombre_sensor2.setSizePolicy(sizePolicy)
        self.nombre_sensor2.setObjectName("nombre_sensor2")
        self.boton_sensor1 = QtWidgets.QPushButton(self.frame_1)
        self.boton_sensor1.setGeometry(QtCore.QRect(100, 70, 170, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_sensor1.sizePolicy().hasHeightForWidth())
        self.boton_sensor1.setSizePolicy(sizePolicy)
        self.boton_sensor1.setStyleSheet("border-image: url(:/cct/sensor1.png);")
        self.boton_sensor1.setText("")
        self.boton_sensor1.setObjectName("boton_sensor1")
        self.boton_sensor2 = QtWidgets.QPushButton(self.frame_1)
        self.boton_sensor2.setGeometry(QtCore.QRect(410, 70, 240, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_sensor2.sizePolicy().hasHeightForWidth())
        self.boton_sensor2.setSizePolicy(sizePolicy)
        self.boton_sensor2.setStyleSheet("border-image: url(:/cct/bombilla.png);")
        self.boton_sensor2.setText("")
        self.boton_sensor2.setObjectName("boton_sensor2")
        self.label_8 = QtWidgets.QLabel(self.frame_1)
        self.label_8.setGeometry(QtCore.QRect(20, 330, 131, 31))
        self.label_8.setObjectName("label_8")
        self.direccion_MAC = QtWidgets.QPlainTextEdit(self.frame_1)
        self.direccion_MAC.setGeometry(QtCore.QRect(150, 330, 151, 31))
        self.direccion_MAC.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.direccion_MAC.setObjectName("direccion_MAC")
        self.boton_conectar_sensor = QtWidgets.QPushButton(self.frame_1)
        self.boton_conectar_sensor.setGeometry(QtCore.QRect(90, 390, 131, 30))
        self.boton_conectar_sensor.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.boton_conectar_sensor.setObjectName("boton_conectar_sensor")
        self.mensaje_mac = QtWidgets.QLineEdit(self.frame_1)
        self.mensaje_mac.setGeometry(QtCore.QRect(20, 430, 371, 32))
        self.mensaje_mac.setObjectName("mensaje_mac")
        self.stackedWidget.addWidget(self.home)
        self.sensor1_1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor1_1.sizePolicy().hasHeightForWidth())
        self.sensor1_1.setSizePolicy(sizePolicy)
        self.sensor1_1.setObjectName("sensor1_1")
        self.frame_2 = QtWidgets.QFrame(self.sensor1_1)
        self.frame_2.setGeometry(QtCore.QRect(0, -20, 741, 681))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.botonMedida = QtWidgets.QPushButton(self.frame_2)
        self.botonMedida.setGeometry(QtCore.QRect(470, 250, 101, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonMedida.sizePolicy().hasHeightForWidth())
        self.botonMedida.setSizePolicy(sizePolicy)
        self.botonMedida.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.botonMedida.setObjectName("botonMedida")
        self.medidaautomatica = QtWidgets.QCheckBox(self.frame_2)
        self.medidaautomatica.setGeometry(QtCore.QRect(170, 500, 281, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.medidaautomatica.sizePolicy().hasHeightForWidth())
        self.medidaautomatica.setSizePolicy(sizePolicy)
        self.medidaautomatica.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.medidaautomatica.setObjectName("medidaautomatica")
        self.Temperatura = QtWidgets.QLineEdit(self.frame_2)
        self.Temperatura.setGeometry(QtCore.QRect(261, 161, 140, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Temperatura.sizePolicy().hasHeightForWidth())
        self.Temperatura.setSizePolicy(sizePolicy)
        self.Temperatura.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Temperatura.setObjectName("Temperatura")
        self.Humedad = QtWidgets.QLineEdit(self.frame_2)
        self.Humedad.setGeometry(QtCore.QRect(261, 225, 140, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Humedad.sizePolicy().hasHeightForWidth())
        self.Humedad.setSizePolicy(sizePolicy)
        self.Humedad.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Humedad.setObjectName("Humedad")
        self.Bateria = QtWidgets.QLineEdit(self.frame_2)
        self.Bateria.setGeometry(QtCore.QRect(261, 289, 140, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bateria.sizePolicy().hasHeightForWidth())
        self.Bateria.setSizePolicy(sizePolicy)
        self.Bateria.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Bateria.setObjectName("Bateria")
        self.Voltaje = QtWidgets.QLineEdit(self.frame_2)
        self.Voltaje.setGeometry(QtCore.QRect(261, 352, 140, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Voltaje.sizePolicy().hasHeightForWidth())
        self.Voltaje.setSizePolicy(sizePolicy)
        self.Voltaje.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Voltaje.setObjectName("Voltaje")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(270, 50, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(111, 151, 133, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox.setGeometry(QtCore.QRect(450, 500, 50, 31))
        self.spinBox.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(900)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setDisplayIntegerBase(10)
        self.spinBox.setObjectName("spinBox")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(500, 500, 41, 31))
        self.label_9.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.sensor1_1)
        self.sensor1_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor1_2.sizePolicy().hasHeightForWidth())
        self.sensor1_2.setSizePolicy(sizePolicy)
        self.sensor1_2.setObjectName("sensor1_2")
        self.label_6 = QtWidgets.QLabel(self.sensor1_2)
        self.label_6.setGeometry(QtCore.QRect(270, 30, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.grafica = Grafica(self.sensor1_2)
        self.grafica.setGeometry(QtCore.QRect(40, 80, 641, 471))
        self.grafica.setObjectName("grafica")
        self.stackedWidget.addWidget(self.sensor1_2)
        self.sensor1_3 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor1_3.sizePolicy().hasHeightForWidth())
        self.sensor1_3.setSizePolicy(sizePolicy)
        self.sensor1_3.setObjectName("sensor1_3")
        self.label_7 = QtWidgets.QLabel(self.sensor1_3)
        self.label_7.setGeometry(QtCore.QRect(270, 30, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.tabla_sensor = QtWidgets.QTableWidget(self.sensor1_3)
        self.tabla_sensor.setGeometry(QtCore.QRect(30, 70, 651, 431))
        self.tabla_sensor.setAutoFillBackground(False)
        self.tabla_sensor.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.tabla_sensor.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tabla_sensor.setObjectName("tabla_sensor")
        self.tabla_sensor.setColumnCount(5)
        self.tabla_sensor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_sensor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_sensor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_sensor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_sensor.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_sensor.setHorizontalHeaderItem(4, item)
        self.tabla_sensor.horizontalHeader().setDefaultSectionSize(130)
        self.boton_borrartabla_entera = QtWidgets.QPushButton(self.sensor1_3)
        self.boton_borrartabla_entera.setGeometry(QtCore.QRect(450, 520, 121, 41))
        self.boton_borrartabla_entera.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.boton_borrartabla_entera.setObjectName("boton_borrartabla_entera")
        self.boton_borrartabla_ultimo = QtWidgets.QPushButton(self.sensor1_3)
        self.boton_borrartabla_ultimo.setGeometry(QtCore.QRect(170, 520, 121, 41))
        self.boton_borrartabla_ultimo.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.boton_borrartabla_ultimo.setObjectName("boton_borrartabla_ultimo")
        self.stackedWidget.addWidget(self.sensor1_3)
        self.sensor2_1 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor2_1.sizePolicy().hasHeightForWidth())
        self.sensor2_1.setSizePolicy(sizePolicy)
        self.sensor2_1.setObjectName("sensor2_1")
        self.nombre_sensor2_2 = QtWidgets.QLabel(self.sensor2_1)
        self.nombre_sensor2_2.setGeometry(QtCore.QRect(270, 30, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nombre_sensor2_2.sizePolicy().hasHeightForWidth())
        self.nombre_sensor2_2.setSizePolicy(sizePolicy)
        self.nombre_sensor2_2.setObjectName("nombre_sensor2_2")
        self.boton_on = QtWidgets.QPushButton(self.sensor2_1)
        self.boton_on.setGeometry(QtCore.QRect(150, 180, 111, 71))
        self.boton_on.setStyleSheet("background-color: rgb(170, 170, 255);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/cct/iconos/light-bulb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_on.setIcon(icon6)
        self.boton_on.setObjectName("boton_on")
        self.boton_off = QtWidgets.QPushButton(self.sensor2_1)
        self.boton_off.setGeometry(QtCore.QRect(470, 180, 111, 71))
        self.boton_off.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.boton_off.setIcon(icon6)
        self.boton_off.setObjectName("boton_off")
        self.label_10 = QtWidgets.QLabel(self.sensor2_1)
        self.label_10.setGeometry(QtCore.QRect(180, 350, 251, 51))
        self.label_10.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_10.setObjectName("label_10")
        self.boton_brillo = QtWidgets.QPushButton(self.sensor2_1)
        self.boton_brillo.setGeometry(QtCore.QRect(560, 350, 101, 51))
        self.boton_brillo.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.boton_brillo.setObjectName("boton_brillo")
        self.textEdit = QtWidgets.QTextEdit(self.sensor2_1)
        self.textEdit.setGeometry(QtCore.QRect(430, 350, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.textEdit.setObjectName("textEdit")
        self.mensaje_brillo = QtWidgets.QLineEdit(self.sensor2_1)
        self.mensaje_brillo.setGeometry(QtCore.QRect(260, 420, 371, 32))
        self.mensaje_brillo.setObjectName("mensaje_brillo")
        self.label_16 = QtWidgets.QLabel(self.sensor2_1)
        self.label_16.setGeometry(QtCore.QRect(120, 350, 61, 51))
        self.label_16.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-image: url(:/cct/iconos/sun.png);")
        self.label_16.setObjectName("label_16")
        self.stackedWidget.addWidget(self.sensor2_1)
        self.Pagina_Auto = QtWidgets.QWidget()
        self.Pagina_Auto.setObjectName("Pagina_Auto")
        self.label_11 = QtWidgets.QLabel(self.Pagina_Auto)
        self.label_11.setGeometry(QtCore.QRect(140, 230, 231, 41))
        self.label_11.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_11.setObjectName("label_11")
        self.modoAuto = QtWidgets.QCheckBox(self.Pagina_Auto)
        self.modoAuto.setGeometry(QtCore.QRect(500, 270, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modoAuto.sizePolicy().hasHeightForWidth())
        self.modoAuto.setSizePolicy(sizePolicy)
        self.modoAuto.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"font: 75 italic 14pt \"PibotoLt\";")
        self.modoAuto.setObjectName("modoAuto")
        self.label_12 = QtWidgets.QLabel(self.Pagina_Auto)
        self.label_12.setGeometry(QtCore.QRect(150, 310, 221, 41))
        self.label_12.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.Pagina_Auto)
        self.label_13.setGeometry(QtCore.QRect(270, 30, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.spinBox_humedad = QtWidgets.QSpinBox(self.Pagina_Auto)
        self.spinBox_humedad.setGeometry(QtCore.QRect(370, 230, 61, 41))
        self.spinBox_humedad.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.spinBox_humedad.setMinimum(1)
        self.spinBox_humedad.setMaximum(100)
        self.spinBox_humedad.setProperty("value", 1)
        self.spinBox_humedad.setDisplayIntegerBase(10)
        self.spinBox_humedad.setObjectName("spinBox_humedad")
        self.spinBox_brillo = QtWidgets.QSpinBox(self.Pagina_Auto)
        self.spinBox_brillo.setGeometry(QtCore.QRect(370, 310, 61, 41))
        self.spinBox_brillo.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.spinBox_brillo.setMinimum(1)
        self.spinBox_brillo.setMaximum(254)
        self.spinBox_brillo.setProperty("value", 1)
        self.spinBox_brillo.setDisplayIntegerBase(10)
        self.spinBox_brillo.setObjectName("spinBox_brillo")
        self.label_14 = QtWidgets.QLabel(self.Pagina_Auto)
        self.label_14.setGeometry(QtCore.QRect(100, 230, 41, 41))
        self.label_14.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-image: url(:/cct/iconos/tint-drop.png);\n"
"")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.Pagina_Auto)
        self.label_15.setGeometry(QtCore.QRect(100, 310, 51, 41))
        self.label_15.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"border-image: url(:/cct/iconos/light-bulb.png);\n"
"")
        self.label_15.setObjectName("label_15")
        self.stackedWidget.addWidget(self.Pagina_Auto)
        self.barra_superior = QtWidgets.QFrame(self.centralwidget)
        self.barra_superior.setGeometry(QtCore.QRect(170, 0, 731, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barra_superior.sizePolicy().hasHeightForWidth())
        self.barra_superior.setSizePolicy(sizePolicy)
        self.barra_superior.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.barra_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.barra_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.barra_superior.setObjectName("barra_superior")
        self.boton_minimizar = QtWidgets.QPushButton(self.barra_superior)
        self.boton_minimizar.setGeometry(QtCore.QRect(660, 0, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_minimizar.sizePolicy().hasHeightForWidth())
        self.boton_minimizar.setSizePolicy(sizePolicy)
        self.boton_minimizar.setStyleSheet("border-image: url(:/cct/iconos/minus-symbol.png);\n"
"\n"
"")
        self.boton_minimizar.setText("")
        self.boton_minimizar.setObjectName("boton_minimizar")
        self.boton_cerrar = QtWidgets.QPushButton(self.barra_superior)
        self.boton_cerrar.setGeometry(QtCore.QRect(700, 0, 31, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_cerrar.sizePolicy().hasHeightForWidth())
        self.boton_cerrar.setSizePolicy(sizePolicy)
        self.boton_cerrar.setStyleSheet("border-image: url(:/cct/iconos/remove-symbol.png);")
        self.boton_cerrar.setText("")
        self.boton_cerrar.setObjectName("boton_cerrar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.menu.setCurrentIndex(2)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botonInicio.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/iconos/home.png\"/></p></body></html>"))
        self.boton1_1.setText(_translate("MainWindow", "Datos Actuales"))
        self.boton1_2.setText(_translate("MainWindow", "Gráfica"))
        self.boton1_3.setText(_translate("MainWindow", "Tabla"))
        self.menu.setItemText(self.menu.indexOf(self.Sensor1), _translate("MainWindow", "Sensor Xiaomi"))
        self.Sensor2.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.boton2_1.setText(_translate("MainWindow", "Control"))
        self.menu.setItemText(self.menu.indexOf(self.Sensor2), _translate("MainWindow", "Bombilla Philips"))
        self.boton_auto.setText(_translate("MainWindow", "Modo Auto"))
        self.menu.setItemText(self.menu.indexOf(self.ModoAuto), _translate("MainWindow", "Modo Automático"))
        self.boton_buscar.setText(_translate("MainWindow", "Buscar dispositivos"))
        self.nombre_sensor1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Xiaomi LYWSD03MMC</span></p></body></html>"))
        self.nombre_sensor2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Philips Hue Bombilla E27</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aaaaff;\">Introduce la MAC</span></p></body></html>"))
        self.boton_conectar_sensor.setText(_translate("MainWindow", "Conectar sensor"))
        self.botonMedida.setText(_translate("MainWindow", "Tomar\n"
" medida"))
        self.medidaautomatica.setText(_translate("MainWindow", "Tomar medida automática cada:"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Xiaomi LYWSD03MMC</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aaaaff;\">Temperatura (ºC)</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aaaaff;\">Humedad (%)</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aaaaff;\">Bateria (%)</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aaaaff;\">Voltaje Bateria (V)</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", " min"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Xiaomi LYWSD03MMC</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Xiaomi LYWSD03MMC</span></p></body></html>"))
        item = self.tabla_sensor.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fecha"))
        item = self.tabla_sensor.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hora"))
        item = self.tabla_sensor.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Temperatura (ºC)"))
        item = self.tabla_sensor.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Humedad (%)"))
        item = self.tabla_sensor.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Batería (%)"))
        self.boton_borrartabla_entera.setText(_translate("MainWindow", "Borrar todo"))
        self.boton_borrartabla_ultimo.setText(_translate("MainWindow", "Borrar último"))
        self.nombre_sensor2_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Philips Hue Bombilla E27</span></p></body></html>"))
        self.boton_on.setText(_translate("MainWindow", "ON"))
        self.boton_off.setText(_translate("MainWindow", "OFF"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Introduce el nivel de brillo deseado </p></body></html>"))
        self.boton_brillo.setText(_translate("MainWindow", "Aplicar"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Introduce el nivel de humedad </p></body></html>"))
        self.modoAuto.setText(_translate("MainWindow", "Modo auto"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Introduce el nivel de brillo</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ffffff;\">Modo Automático</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))

from grafica import Grafica
import icons_rc
